FROM ubuntu
ENV FRONT_URL=http://localhost:5000 
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y curl git nodejs npm tzdata
RUN git clone https://github.com/docker-hy/backend-example-docker
RUN adduser -D backusr && chown backusr /backend-example-docker
WORKDIR ./backend-example-docker
USER backusr
RUN npm install
EXPOSE 8000
CMD npm start
