FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y curl git nodejs npm tzdata
RUN git clone https://github.com/docker-hy/frontend-example-docker
RUN adduser -D frontusr && chown frontusr /frontend-example-docker
WORKDIR ./frontend-example-docker
ENV API_URL=http://localhost:8000
USER frontusr
RUN npm install
EXPOSE 8000
CMD npm start

