version: '3.5'

services:
  backend:
    build:
      context: .
      network: host
      dockerfile: Dockerfile_backend
    ports:
      - 8000:8000
  frontend:
    build:
      context: .
      network: host
      dockerfile: Dockerfile_frontend
    ports:
      - 5000:5000
